services:
  # fastapi
  api:
    container_name: "test_fast-api"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: dev
    env_file: .env
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./app
          target: /project/app
        - action: rebuild
          path: ./pyproject.toml
    volumes:
      - ./tests:/project/tests
    depends_on:
      - db
  # db
  db:
    container_name: "test_fast-db"
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:
